services:
  - type: web
    name: background-removal-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6